#!/bin/bash

DIV="--------------------------"
PRUNE=""

# Directory where all the repos are stored, update if needed
REPOS_DIR="{HOME}/repos"

while getopts "p" OPTION; do
    case $OPTION in
        p)
            PRUNE="-p"
            ;;
    esac
done

echo "FETCH ALL REPOS\n\
in the directory: ${REPOS_DIR}"

for REPO in $(ls $REPOS_DIR); do
    echo "$DIV"
    cd "$REPOS_DIR/$REPO"
    echo "Fetching repo: $REPO..."
    git fetch $PRUNE
done