#!/bin/bash

DIV="--------------------------"
PRUNE=""

# Directory where all the repos are stored, update if needed
REPOS_DIR="${HOME}/repos"

while getopts "p" OPTION; do
    case $OPTION in
        p)
            PRUNE="-p"
            ;;
    esac
done

shift $((OPTIND-1))

# Try to read the repos directory from the command line
if [ -n "$1" ]; then
    REPOS_DIR="$1"
fi

echo "FETCH ALL REPOS IN ${REPOS_DIR}"

for REPO in $(ls $REPOS_DIR); do
    REPO_PATH="${REPOS_DIR}/${REPO}"
    if [ ! -d $REPO_PATH ]; then
        continue
    fi

    echo "$DIV"
    cd $REPO_PATH && \
    echo "Fetching repo: $REPO..." && \
    git fetch $PRUNE
done